### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by crinny** [thomas-crane/nrelay#17]
### Version info
 + nrelay version: `7`
 + RotMG version: `X29.0.1`

### Plugins
 + HelloPlugin (edited)
    + Uses packets
        + `TradeRequestedPacket`

### Steps to reproduce
1. Start nrelay

### Result
```
[14:48:59 | PluginManager]    Error while loading hello-plugin.js
C:\Users\HP\Desktop\Stuff\nrelay\dist\plugins\hello-plugin.js:2
import { Client, Library, PacketHook } from './../core';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Function.loadPlugins (C:\Users\HP\Desktop\Stuff\nrelay\dist\core\library-manager.js:32:17)
```

**Comment by thomas-crane** [comment]
It seems like you might have put some TypeScript code into a JavaScript file.

```typescript
import { Client, Library, PacketHook } from './../core';
```
Is TypeScript (or ES6 JS) syntax, so it should always be placed in a TypeScript file (`.ts` extension).

Just to clarify,

+ `nrelay/src/plugins/` Is where you should be working when making plugins, and should only ever have TypeScript files in the folder.
+ `nrelay/dist/plugins` Is generated as a result of running `npm run build`, and should only contain the compiled TypeScript.

The `dist/` folder will be deleted and regenerated every time you run `npm run build`, so you should never edit any files in that folder.

**Comment by crinny** [comment]
@thomas-crane Sorry for writing it in issue, but i didn't find any your contacts. Is it possible to add accounts via plugin?

**Comment by thomas-crane** [comment]
@crinny Yes, it is. If you have Discord I am happy to discuss further with you there. Please add me at `Killer Be Killed#1781`
