### ISSUE TITLE
Reconnect packet issue with X21.0.0

### ISSUE THREAD

**Issue by armst198** [thomas-crane/nrelay#2]
### Version info
 + nrelay version: `6.4.6`
 + RotMG version: `X21.0.0`

### Plugins
 + Unnamed (_unreleased_)
    + Uses packets
        + `ReconnectPacket`
        + `UpdatePacket`
        + `UsePortalPacket`
        + `EscapePacket`

### Steps to reproduce
1. Start nrelay
2. Send a UsePortalPacket

### Result
```
The bot crashes with the error:
RangeError: Invalid typed array length: -11008
    at typedArrayConstructByLength (<anonymous>)
    at new Int8Array (native)
    at ReconnectPacket.read (/home/rotmg/nrelay/dist/networking/packets/incoming/reconnect-packet.js:19:20)
    at PacketIO.emitPacket (/home/rotmg/nrelay/dist/networking/packetio.js:123:20)
    at PacketIO.processData (/home/rotmg/nrelay/dist/networking/packetio.js:102:22)
```
### Fix
Server is now sending stats in the reconnect packet. Declare a stats string and change src/networking/packets/incoming/reconnect-packet.ts to:
```
this.host = this.readString();
this.stats = this.readString();
this.port = this.readInt32();
```

**Comment by thomas-crane** [comment]
Fixed and tested in `6.4.7`. Thanks for providing the fix.
