### ISSUE TITLE
JDK 11 Issue

### ISSUE THREAD

**Issue by Kosta-Git** [thomas-crane/nrelay#32]
### Version info
 + nrelay version: `Latest Dev branch`
 + RotMG version: `X31.7.0`

### JDK 11 (Only tested on ubuntu)
nrelay run will cause issues on jdk 11 sample just under

```
[18:00:17 | Runtime]          Error while updating: Command failed: sudo java -jar --illegal-access=permit "/media/me/D2/rotmg-projects/nrelay/multi/node_modules/@realmlib/resx/lib/jpexs/ffdec.jar" -selectclass kabam.rotmg.messaging.impl.GameServerConnection -export script "/media/me/D2/rotmg-projects/nrelay/multi/temp/decompiled" "/media/me/D2/rotmg-projects/nrelay/multi/temp/client.swf"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jpexs.decompiler.flash.configuration.Configuration (file:/media/me/D2/rotmg-projects/nrelay/multi/node_modules/@realmlib/resx/lib/jpexs/lib/ffdec_lib.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of com.jpexs.decompiler.flash.configuration.Configuration
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
May 11, 2019 6:00:17 PM com.jpexs.decompiler.flash.gui.Main main
SEVERE: Failed to load plugins
java.lang.Error: Can not set static final com.jpexs.decompiler.flash.configuration.ConfigurationItem field com.jpexs.decompiler.flash.configuration.Configuration.registerNameFormat to com.jpexs.decompiler.flash.configuration.ConfigurationItem
	at com.jpexs.decompiler.flash.configuration.Configuration.setConfigurationFields(Configuration.java:889)
	at com.jpexs.decompiler.flash.configuration.Configuration.<clinit>(Configuration.java:839)
	at com.jpexs.decompiler.flash.helpers.SWFDecompilerPlugin.getPluginsDir(SWFDecompilerPlugin.java:61)
	at com.jpexs.decompiler.flash.helpers.SWFDecompilerPlugin.loadPlugins(SWFDecompilerPlugin.java:78)
	at com.jpexs.decompiler.flash.gui.Main.main(Main.java:1915)

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.jpexs.decompiler.flash.configuration.Configuration
	at com.jpexs.decompiler.flash.gui.Main.main(Main.java:1921)
```

I tried adding `sudo` as well as `--illegal-access=permit` to solve the issue but it did not solve it.
The fix I found at the moment was to change to JDK 8 which will run everything smoothly.

**Comment by thomas-crane** [comment]
I've done a bit of Googling, and it seems like this is more of an issue with JPEXS than nrelay. Other people have reported issues with JPEXS on JDK 9, 10 and 11, and the author's response is generally always just "Downgrade to JDK 8 if possible".

I'll be removing the dependency on Java fairly soon thanks to some awesome work done by @dmarcuse but unfortunately the best answer I can give you right now is just to sit tight and downgrade to JDK 8 if you can!

**Comment by thomas-crane** [comment]
Hey @Kosta-Git, I've just pushed version 8.3.4 (aaefceb483640132084ba61e8399d5b19db8b2c2) which removes the dependency on Java all together.

You should just be able to use `nrelay update` to get this new version. Let me know if you have any issues with the new updater!
